events {
    worker_connections 1024;
}

http {
    # включается типы данных
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    server {
        listen 80;
        server_name localhost;

        # 1. Главный прокси на Django (обрабатывает все запросы)
        location / {
            proxy_pass http://web:8000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        # 2. Раздача статики Django (админка, стили моего каталога)
        location /static/ {
            alias /var/www/html/static/;
        }

        # 3. Раздача медиа-файлов (если пользователи будут загружать картинки)
        location /media/ {
            alias /var/www/html/media/;
        }
    }
}