# Generated by Django 6.0.5 on 2026-05-25 17:16

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Habit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        max_length=255, verbose_name="Место выполнения привычки"
                    ),
                ),
                ("time", models.TimeField(verbose_name="Время выполнения привычки")),
                ("action", models.TextField(verbose_name="Действие привычки")),
                (
                    "is_pleasant",
                    models.BooleanField(
                        default=False, verbose_name="Признак приятной привычки"
                    ),
                ),
                (
                    "compensation",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Вознаграждение",
                    ),
                ),
                (
                    "regularity",
                    models.IntegerField(default=1, verbose_name="Периодичность в днях"),
                ),
                (
                    "time_required",
                    models.DurationField(
                        default=datetime.timedelta(seconds=120),
                        verbose_name="Время на выполнение",
                    ),
                ),
                (
                    "public",
                    models.BooleanField(
                        default=True, verbose_name="Признак публичности"
                    ),
                ),
                (
                    "related_habit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="habit_tracker.habit",
                        verbose_name="Связанная привычка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Привычка",
                "verbose_name_plural": "Привычки",
            },
        ),
    ]
